<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PagesTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        DB::table('pages')->truncate();
        $article = [
        [
        'title' => 'The Qnique Quilter Makes it Easy to Create Quilting Masterpieces',
        'slug' => Str::slug('qnique-quilter-makes-masterpieces'),
        'content' => 'From early times women have sewn quilts from leftover bits of fabric to cover their beds and keep their families warm, but the sewing was done by hand since they did not have sewing machines then. The work was tedious and it took many hours to finish just one quilt. Women often got help from their neighbors and family members to finish the quilt in just one day, and each member of the group got help in making their own quilt. These gatherings were known as quilting bees, and served as social activities as well as work days. The modern sewing machine has made sewing a quilt much faster and easier than in pioneer days, but it is still necessary for a quilter to learn the intricate details of the art. It takes much more than looking through pattern books to find the right piece and then following the directions to make the quilt. Today\'s quilting machine is equipped with multiple accessories, so the operator must learn how to use them correctly. <h2 itemprop="hasPart about">A New Quilting Machine</h2> The intricate stitches needed to create beautiful patterns on quilts should be uniform in length and consistency, and the Qnique Quilter\'s built-in regulation ensures perfect stitches. Highly detailed patterns are not difficult to create using this state of the art machine that uses laser technology to exactly follow the outline of images or patterns. Learning to use the Qunique Quilter is relatively easy by following the directions in the instruction books that are included, and online advice is always available. The Qnique Quilter is a state of the art machine that gives the operator all the tools needed to create pieces that are beautiful enough to sell at craft shows or online. Many women even find a satisfying career in making and selling quilts, and the Qnique Quilter can make this occupation much easier and more profitable. People who sew quilts and accessories at home to sell at shows or online are able to turn out more finished projects when they have a quilting frame. This modern machine is designed to work perfectly on many existing frames, and includes at complete set of instructions to set it up on various quilting frames. <h2 itemprop="hasPart about">Low Priced Quilting Machine</h2> Considering the many benefits of owning a Qnique Quilter, prospective buyers might be concerned about its high cost. The cost of comparable longarm quilting machines typically falls between $6,000 to $18,000, but the Qnique Quilter can be purchased for much less then others. This is an incredibly reasonable price even though the Qnique offers all the advantages of the higher price machines, plus finger-tip controls for ease of operation. Although the Qnique is not classified as a longarm machine, its 15" throat length offers the operator the ability to sew most patterns effortlessly. Quilting is a creative hobby that many women enjoy, and they make lovely quilts and accessories for their own home or as gifts. Other women have begun to sell their beautiful projects at shows, in a local quilt shop or online. Unless a quilter is focused on sewing and selling quilts and accessories as a career, she may not have considered purchasing a quilting machine for her home. However, the reasonable cost and high performance level of the Qnique Quilter could make the purchase a possibility. Although it is not likely that anyone who purchases this machine would want to return it, the company policy does have a return policy due to defects with or dissatisfaction with its performance.',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'The Qnique Quilter Makes it Easy to Create Quilting Masterpieces',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => 'The Qnique Quilter Makes it Easy to Create Quilting Masterpieces',
        'gp_title' => 'The Qnique Quilter Makes it Easy to Create Quilting Masterpieces',
        'tw_title' => 'The Qnique Quilter Makes it Easy to Create Quilting Masterpieces',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'],
        [
        'title' => 'About Us',
        'slug' => Str::slug('about-us'),
        'content' => '<h2 itemprop="hasPart about">The Grace Company</h2> <p>For many companies, innovation and invention are the foundation on which success is built.  This has been a key component in the quilting industry, which has seen a dramatic transformation due to technology that has made the process of quilting easier for those who possess a passion for the craft.  Over the past 25 years, The Grace Company has taken innovation and invention to entirely new levels with its commitment to integrating the worlds of quilting and technology.  The results have been products that have not only revolutionized the industry, but also given those with a love of quilting the ability to create masterpieces almost beyond belief.  With their commitment to customer service and always being willing to take a concept and develop it into yet another product to satisfy their customers, The Grace Company has started a tradition of excellence that has no end in sight. </p> <h2 itemprop="hasPart about">Quilting Frames</h2> <p>To create any quilt, a quilting frame is required to make the task possible. The Grace Company, having developed a line of quilting frames unlike any previously seen, quickly became the go-to company for those needing the best possible equipment.  With both machine-quilting and hand-quilting frames from which to choose, customers soon found themselves with a variety of possibilities when it came to quilting.   The frames offered numerous advantages to customers, including:</p> <ul> <li>Professional-quality rail system</li> <li>Improved fabric tension</li> <li>Height adjustment to fit sewing machines</li> <li>Speed control and stitch regulators</li> </ul> <strong>With the introduction of these features, Grace quickly became the company associated with quilting quality and began its ascension to the top.</strong> <h2 itemprop="hasPart about">Computerized Technology</h2> <p>However, what truly set The Grace Company apart from other competitors was its embracing of computerized technology when it came to quilting. With its development of quilting pattern software, the company made it possible to see how a design would look before the first stitch was sewed.  In doing so, quilts could contain designs that were more intricate than ever before, and as a bonus would take far less time and effort than in previous years.  Some of the most popular quilting software programs have included:</p> <ul> <li>QuiltMotion</li> <li>Quilter\'s Creative Touch</li> <li>Quilter\'s Creative Design</li> </ul> <p>With numerous testimonials from thousands of satisfied customers, The Grace Company has led the way for those who wish to continue combining traditional quilting methods with today\'s technology. And for those who have used the equipment as well as those who have viewed the masterpieces that have been made, the results speak for themselves.</p>',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'About Us',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => 'About The Grace Company',
        'gp_title' => 'About The Grace Company',
        'tw_title' => 'About The Grace Company',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'
        ],
        [
        'title' => 'Returns Policy',
        'slug' => Str::slug('returns'),
        'content' => '<p>All returns require a Return Merchandise Authorization Number, which you should be given upon notification of your return.  Please reference this number on your returned item.  A restocking fee of up to 25% may apply to used, non-defective returns. </p> <em><strong>*The customer is responsible for all shipping costs.</strong></em> <p>**Grace Products purchased from our dealers are subject to the Dealer’s refund policies. However, with our warranty we stand behind our products warranties, whether purchased direct from us or any of our reputable dealers (see below). We also handle all part replacement and technical support direct. Simply call us toll-free 1 800 264 0644, for technical support and replacement parts needs.</p> <h3>International Shipping</h3> <p>GraceWood INC, is not responsible for any custom, duties, brokerage, taxes, or any other charges that may occur with International shipping</p>',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'Returns Policy',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => 'Returns Policy',
        'gp_title' => 'Returns Policy',
        'tw_title' => 'Returns Policy',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'
        ],
        [
        'title' => 'Copyright',
        'slug' => Str::slug('copyright'),
        'content' => '<p>  All material contained on the <strong>The Grace Company</strong> site is covered by a disclaimer and protected by <strong>US</strong>&nbsp;and international copyright laws. Access to the website is subject to your agreement to the following:&nbsp;</p> <p>The <strong>The Grace Company</strong> website is designed for information purposes only.</p> <p>Users must not reproduce, download, store in any medium, distribute, transmit or re-transmit or manipulate any text except for the purposes of research or private study. Reproduction for any other purpose is not permitted without written permission which must be obtained in advance from the Copyright Manager, The Grace Company, 2225 South 3200 ste Q, West Salt Lake City, <strong>UT</strong> 84119. Tel (800) 264-0644.</p> <p>All brand names, publishing activities and trade marks used on these webpages are the trade marks, service marks or trade names of their respective holders.</p> <p><strong>The Grace Company</strong> makes no warranties or representations about the accuracy of any information on this website or any other website to which it may be linked. The information contained in these pages is for general information only and <strong>The Grace Company</strong> shall not be liable for the accuracy, quality or completeness of any information contained in this website.</p> <p>You are granted access to these pages conditional upon your agreement to indemnify the <strong>The Grace Company</strong> and not to hold the company liable in any way for the results of any action you may take based on the material contained herein.</p> <p>English law governs all matters between us in relation to this website and all claims or disputes arising out of or in connection with this web site shall be subject to the exclusive jurisdiction of the courts of Utah.</p> <p>Text in this website is copyright © <strong>The Grace Company 2014</strong>. </p> <p>No photographs on this website may be reproduced for any purpose without prior permission which must be obtained in writing from <strong>The Grace Company</strong> or The Grace Company.</p>',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'Copyright',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => 'Copyright',
        'gp_title' => 'Copyright',
        'tw_title' => 'Copyright',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'
        ],
        [
        'title' => 'Warranty',
        'slug' => Str::slug('warranty'),
        'content' => '<p><strong>The Grace Company guarantees these electrical parts against manufacturing defects for the first year of ownership on all Qnique models.</strong></p> <p>The Grace Company warrants all non-moving, non-electric, mechanical parts on the Qnique Quilting Machine against mechanical failure due to manufacturing defects for up to 2 years after initial purchase.The Grace Company warrants the cast metal body of the Qnique Quilting Machine to be free of defects or imperfections causing product failure for up to 5 years after initial purchase. </p> <p>This means <strong>Grace Company</strong> will replace parts that they deem to be faulty, or that fail due to what the Grace Company determines to be manufacturing defects. The customer pays all shipping and labor fees. The warranty period begins at the date of purchase. The warranty does not transfer to a secondary owner.</p> <strong>Any parts damaged by the customer do require payment.</strong> <p>The Warranty period begins at the time of the customer’s purchase from <strong>Grace Company</strong> or a dealer (not from the time of the dealer’s purchase). Customer proof of purchase should be obtained if no warranty card for the customer exists.</p> <p><strong>Warranty Exclusions:</strong> The warranty does not apply to any costs, repairs, or services for repairs necessitated by use other than normal home use, or damage resulting from misuse, abuse, accidents, alterations, or lack of proper machine maintenance.</p> <strong>Warranty Info:The following electrical parts on the Qnique Grace Sewing Machine System have a 1-year limited warranty:</strong> <ul> <li>Front Handles/Buttons</li> <li>LCD, Encoders</li> <li>Laser</li> <li>Stitch Regulator</li> <li>Cables</li> <li>Power Supply</li> <li>Motor</li> <li>All other wiring and electronics.</li> </ul>',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'Warranty',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => 'Warranty',
        'gp_title' => 'Warranty',
        'tw_title' => 'Warranty',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'
        ],
        [
        'title' => 'Company Disclaimers',
        'slug' => Str::slug('company-disclaimers'),
        'content' => '<h2>Disclaimer</h2> <p>The information contained in http://www.graceframe.com is for general information purposes only. The information is provided by http://www.graceframe.com and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to http://www.graceframe.com or the information, products, services, or related graphics contained on http://www.graceframe.com for any purpose. Any reliance you place on such information is therefore strictly at your own risk.<br /> <br /> In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of http://www.graceframe.com.<br /> <br /> Through http://www.graceframe.com you are able to link to other websites which are not under the control of http://www.graceframe.com. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.<br /> <br /> Every effort is made to keep http://www.graceframe.com up and running smoothly. However,http://www.graceframe.com takes no responsibility for, and will not be liable for, http://www.graceframe.com being temporarily unavailable due to technical issues beyond our control.<br /> &nbsp;</p> <div style="font-weight: bold;">Earnings Disclaimer</div> <p><br /> <br /> EVERY EFFORT HAS BEEN MADE TO ACCURATELY REPRESENT THIS PRODUCT AND IT&rsquo;S POTENTIAL. EVEN THOUGH THIS INDUSTRY IS ONE OF THE FEW WHERE ONE CAN WRITE THEIR OWN CHECK IN TERMS OF EARNINGS, THERE IS NO GUARANTEE THAT YOU WILL EARN ANY MONEY USING THE TECHNIQUES AND IDEAS IN THESE MATERIALS. EXAMPLES IN THESE MATERIALS ARE NOT TO BE INTERPRETED AS A PROMISE OR GUARANTEE OF EARNINGS. EARNING POTENTIAL IS ENTIRELY DEPENDENT ON THE PERSON USING OUR PRODUCT, IDEAS AND TECHNIQUES. WE DO NOT PURPORT THIS AS A &ldquo;GET RICH SCHEME.&rdquo;<br /> <br /> ANY CLAIMS MADE OF ACTUAL EARNINGS OR EXAMPLES OF ACTUAL RESULTS CAN BE VERIFIED UPON REQUEST. YOUR LEVEL OF SUCCESS IN ATTAINING THE RESULTS CLAIMED IN OUR MATERIALS DEPENDS ON THE TIME YOU DEVOTE TO THE PROGRAM, IDEAS AND TECHNIQUES MENTIONED, YOUR FINANCES, KNOWLEDGE AND VARIOUS SKILLS. SINCE THESE FACTORS DIFFER ACCORDING TO INDIVIDUALS, WE CANNOT GUARANTEE YOUR SUCCESS OR INCOME LEVEL. NOR ARE WE RESPONSIBLE FOR ANY OF YOUR ACTIONS.<br /> <br /> MATERIALS IN OUR PRODUCT AND OUR WEBSITE MAY CONTAIN INFORMATION THAT INCLUDES OR IS BASED UPON FORWARD-LOOKING STATEMENTS WITHIN THE MEANING OF THE SECURITIES LITIGATION REFORM ACT OF 1995. FORWARD-LOOKING STATEMENTS GIVE OUR EXPECTATIONS OR FORECASTS OF FUTURE EVENTS. YOU CAN IDENTIFY THESE STATEMENTS BY THE FACT THAT THEY DO NOT RELATE STRICTLY TO HISTORICAL OR CURRENT FACTS. THEY USE WORDS SUCH AS &ldquo;ANTICIPATE,&rdquo; &ldquo;ESTIMATE,&rdquo; &ldquo;EXPECT,&rdquo; &ldquo;PROJECT,&rdquo; &ldquo;INTEND,&rdquo; &ldquo;PLAN,&rdquo; &ldquo;BELIEVE,&rdquo; AND OTHER WORDS AND TERMS OF SIMILAR MEANING IN CONNECTION WITH A DESCRIPTION OF POTENTIAL EARNINGS OR FINANCIAL PERFORMANCE.<br /> <br /> ANY AND ALL FORWARD LOOKING STATEMENTS HERE OR ON ANY OF OUR SALES MATERIAL ARE INTENDED TO EXPRESS OUR OPINION OF EARNINGS POTENTIAL. MANY FACTORS WILL BE IMPORTANT IN DETERMINING YOUR ACTUAL RESULTS AND NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE RESULTS SIMILAR TO OURS OR ANYBODY ELSES, IN FACT NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE ANY RESULTS FROM OUR IDEAS AND TECHNIQUES IN OUR MATERIAL.<br /> <br /> The author and publisher disclaim any warranties (express or implied), merchantability, or fitness for any particular purpose. The author and publisher shall in no event be held liable to any party for any direct, indirect, punitive, special, incidental or other consequential damages arising directly or indirectly from any use of this material, which is provided &ldquo;as is&rdquo;, and without warranties.<br /> <br /> As always, the advice of a competent legal, tax, accounting or other professional should be sought.<br /> <br /> http://www.graceframe.com does not warrant the performance, effectiveness or applicability of any sites listed or linked to on http://www.graceframe.com<br /> <br /> All links are for information purposes only and are not warranted for content, accuracy or any other implied or explicit purpose.</p> <hr /> <h2>Disclaimer</h2>The information contained in http://www.graceframe.com is for general information purposes only. The information is provided by http://www.graceframe.com and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to http://www.graceframe.com or the information, products, services, or related graphics contained on http://www.graceframe.com for any purpose. Any reliance you place on such information is therefore strictly at your own risk.<br /><br />In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of http://www.graceframe.com.<br /><br />Through http://www.graceframe.com you are able to link to other websites which are not under the control of http://www.graceframe.com. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.<br /><br />Every effort is made to keep http://www.graceframe.com up and running smoothly. However,http://www.graceframe.com takes no responsibility for, and will not be liable for, http://www.graceframe.com being temporarily unavailable due to technical issues beyond our control.<br /><br /><br /> <div style="font-weight: bold;">Earnings Disclaimer</div><br /><br />EVERY EFFORT HAS BEEN MADE TO ACCURATELY REPRESENT THIS PRODUCT AND IT&#39;S POTENTIAL. EVEN THOUGH THIS INDUSTRY IS ONE OF THE FEW WHERE ONE CAN WRITE THEIR OWN CHECK IN TERMS OF EARNINGS, THERE IS NO GUARANTEE THAT YOU WILL EARN ANY MONEY USING THE TECHNIQUES AND IDEAS IN THESE MATERIALS. EXAMPLES IN THESE MATERIALS ARE NOT TO BE INTERPRETED AS A PROMISE OR GUARANTEE OF EARNINGS. EARNING POTENTIAL IS ENTIRELY DEPENDENT ON THE PERSON USING OUR PRODUCT, IDEAS AND TECHNIQUES. WE DO NOT PURPORT THIS AS A "GET RICH SCHEME."<br /> <br /> ANY CLAIMS MADE OF ACTUAL EARNINGS OR EXAMPLES OF ACTUAL RESULTS CAN BE VERIFIED UPON REQUEST. YOUR LEVEL OF SUCCESS IN ATTAINING THE RESULTS CLAIMED IN OUR MATERIALS DEPENDS ON THE TIME YOU DEVOTE TO THE PROGRAM, IDEAS AND TECHNIQUES MENTIONED, YOUR FINANCES, KNOWLEDGE AND VARIOUS SKILLS. SINCE THESE FACTORS DIFFER ACCORDING TO INDIVIDUALS, WE CANNOT GUARANTEE YOUR SUCCESS OR INCOME LEVEL. NOR ARE WE RESPONSIBLE FOR ANY OF YOUR ACTIONS.<br /> <br /> MATERIALS IN OUR PRODUCT AND OUR WEBSITE MAY CONTAIN INFORMATION THAT INCLUDES OR IS BASED UPON FORWARD-LOOKING STATEMENTS WITHIN THE MEANING OF THE SECURITIES LITIGATION REFORM ACT OF 1995. FORWARD-LOOKING STATEMENTS GIVE OUR EXPECTATIONS OR FORECASTS OF FUTURE EVENTS. YOU CAN IDENTIFY THESE STATEMENTS BY THE FACT THAT THEY DO NOT RELATE STRICTLY TO HISTORICAL OR CURRENT FACTS. THEY USE WORDS SUCH AS "ANTICIPATE," "ESTIMATE," "EXPECT," "PROJECT," "INTEND," "PLAN," "BELIEVE," AND OTHER WORDS AND TERMS OF SIMILAR MEANING IN CONNECTION WITH A DESCRIPTION OF POTENTIAL EARNINGS OR FINANCIAL PERFORMANCE.<br /> <br /> ANY AND ALL FORWARD LOOKING STATEMENTS HERE OR ON ANY OF OUR SALES MATERIAL ARE INTENDED TO EXPRESS OUR OPINION OF EARNINGS POTENTIAL. MANY FACTORS WILL BE IMPORTANT IN DETERMINING YOUR ACTUAL RESULTS AND NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE RESULTS SIMILAR TO OURS OR ANYBODY ELSES, IN FACT NO GUARANTEES ARE MADE THAT YOU WILL ACHIEVE ANY RESULTS FROM OUR IDEAS AND TECHNIQUES IN OUR MATERIAL.<br /> <br /> The author and publisher disclaim any warranties (express or implied), merchantability, or fitness for any particular purpose. The author and publisher shall in no event be held liable to any party for any direct, indirect, punitive, special, incidental or other consequential damages arising directly or indirectly from any use of this material, which is provided "as is", and without warranties.<br /> <br /> As always, the advice of a competent legal, tax, accounting or other professional should be sought.<br /> <br /> http://www.graceframe.com does not warrant the performance, effectiveness or applicability of any sites listed or linked to on http://www.graceframe.com<br /> <br /> All links are for information purposes only and are not warranted for content, accuracy or any other implied or explicit purpose. <hr /> <h2>Externmal Links Policy</h2><p>http://www.graceframe.com links to other, external web sites that provide information we determine at our discretion contain the most useful information for our program. While many sites provide very useful information, http://www.graceframe.com only links to those sites which provide the most useful content.</p><p>These links may be changed at any time as more useful sites come to our attention. The sole purpose of any external link is to enrich this site for our customers. All requests for inclusion of a link on this site is first and primarily evaluated with the needs of our customers in mind. Generally, external web sites do not meet the purposes of http://www.graceframe.com if they contain, suggest, or infer any of the following:</p><ol><li>Advocacy of or opposition to any politically, environmentally, or socially controversial subjects, issues, or candidates.</li><li>Disparaging or promoting any person or class of persons.</li><li>External content not suitable for readers or viewers of all ages, or links to or other promotion of businesses whose products or services are not suitable for persons of all ages.</li><li>Promoting or inciting illegal, violent, or socially undesirable conduct.</li><li>Promotion or availability of alcohol or tobacco products.</li><li>Promotion or availability of illegal drugs.</li><li>Promotion or availability of adult or sexually oriented entertainment or materials.</li><li>Promotion, opposition, or availability of weapons.</li><li>Promotion, opposition, or availability of gambling.</li><li>Claims of efficacy, suitability, desirability, or other non-objective statements about businesses, products, or services.</li><li>Content that infringes on any trademark, copyright, or patent rights of another.</li><li>Claims or representations in violation of advertising or consumer protection laws.</li><li>Content that a reasonable citizen may not consider to maintain the dignity and decorum appropriate for government.</li></ol><p>This list is a nonexclusive list. The external link policy applies only to web sites outside http://www.graceframe.com The webmaster shall establish procedures to monitor the implementation and continuing oversight of this policy. These procedures shall include a process for review of all new requests for external content links from http://www.graceframe.com Web page to another page to ensure compliance with this policy prior to granting the request.</p><p>Each request for such a link shall be evaluated using the following guidelines:</p><b>Is the content relevant?</b><br /><p>Does the site provide information or services, which are not already available or linked to on http://www.graceframe.com? If not, is the quality of the site comparable to or better than what is already provided?</p><b>Is the site well designed, easy to use, cross-browser compliant, and accessible to people with disabilities?</b><p>http://www.graceframe.com reserves the right, at its sole discretion and without explanation, to withdraw at any time any external content for any reason.</p><hr />',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'Company Disclaimers',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => 'Company Disclaimers',
        'gp_title' => 'Company Disclaimers',
        'tw_title' => 'Company Disclaimers',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'
        ],
        [
        'title' => 'Shipping Policy',
        'slug' => Str::slug('shipping-policy'),
        'content' => '<p>For select items, we offer an Estimated Delivery Date during checkout. An Estimated Delivery Date is a calculation of several factors, including item availability, processing time in our warehouse, the shipping method you select and the shipping destination. When we can accurately calculate Estimated Delivery Dates, we’ll provide them to you during checkout, as well as in your Order Confirmation email and in the My Account section on the website. Please note that Estimated Delivery Dates are estimates only, and are not guaranteed. Also, if using our Pay in Store payment option, shipping is dependent upon your payment in full at the store. A good rule of thumb is to add 2 additional days if using that option.</p> <p>The delivery time for your order depends on the shipping method you select. We offer several different shipping methods. <br><br><strong>The choices available depend on…</strong></p> <ol> <li><strong>The item(s) purchased.</strong></li> <li><strong>The in-stock availability of the product.</strong></li> <li><strong>The destination address.</strong></li></ol><p>Each shipping method has its own restrictions and charges that will be applied to your order. This is based upon a simple calculation of order processing time and actual shipping time in business days. Please note that business days are Monday through Friday, excluding Federal holidays within the United States.</p> <p>Calculating estimated shipping dates is based on several factors, including your destination address and how quickly we can obtain and assemble items for your shipment (the “usually ships within” time is listed on a product’s detail page to help you gauge how quickly we can ship your order out).</p> <p>To calculate your delivery estimate, simply take the time called out in the “Availability” section on the product detail page (“Usually leaves warehouse in…” or what we refer to as “Processing Time”) and add the time it takes a package to travel from our facilities to your destination address, based on the shipping method you’ve selected. Please note that orders for multiple items or multiple copies of a single item may take longer to assemble before we’re able to ship them to you. Also, please don’t forget to add 2 additional days to the “Usually leaves warehouse in/Processing time” timeframe if using our Pay in Store payment option.<br><br><strong>How Are Oversized Items Handled?</strong></p> <hr class="hd_rule2"> <p>Some heavy or oddly shaped items must be shipped alone using a freight trucking company. <strong><i>Usually, oversized Items arrive in 7-14 full business days after leaving our warehouse</i></strong>. Business days are Monday thru Friday, excluding federal holidays within the United States. Some larger and heavier items can only be sent via ground freight, and it’s important to note that the freight trucking company is not responsible for unloading the item from the truck, or carrying the item inside. Since the item is likely to be heavy and large, we recommend that you have someone with you to help you unload the item. If you are sending this item as a gift, please include the recipient’s phone number so the recipient can be contacted in the event the delivery needs to be scheduled.</p> &nbsp; <strong>Are There Any Rules And Restrictions I Should Know About?</strong> <hr class="hd_rule2"> <p>Please be aware of the following in order to assist you with your shipping selections and needs:</p> <ul> <li><strong><span style="color: #3366ff;"><em>Orders are shipped on business days only (Monday through Friday) excluding federal holidays within the United States.</em></span></strong></li> <li><strong>Your order must be received and your credit card authorized by 12:00 p.m. (noon) EST or your order will not be processed until the following business day. This applies to all shipping methods, including Express Shipping.</strong></li> <li>Expedited Shipping and Express Shipping orders require a street address.</li> <li>Orders paid for with our Pay in Store payment option will not ship until paid in full at our&nbsp;stores. You will be provided with 48 hours in which to pay for your order or your order will be automatically cancelled.</li> <li>Items shipped to the following destinations may only be shipped via the UPS&nbsp;Postal Service and cannot be expedited:</li> <li>Please note that not all items are eligible to ship to APO/FPO/PO Box addresses. Please check individual product detail pages for restrictions.</li> </ul> <p>Please allow for additional shipping and handling time for all oversized products shipping via a freight trucking company.<br><br></p> &nbsp; <strong>How Do I Track My Order?</strong> <hr class="hd_rule2"> <p>Easy! Tracking numbers are assigned to packages at our warehouse almost immediately, and generally appear on our website along with your order information. <strong>It is possible that it may take up to 48 hours or longer before the package is checked into the carrier’s tracking system</strong>. This basically means that even though your package has left<i>our warehouse</i>, the <i>carrier</i> may not be able to provide any information about your package for up to 48 hours or more.</p> <p>To access tracking simply login to the account you created when you purchased the items and look in the tracking section of my account and you will find the information you will need to get the status of your package.</p> <p><strong>Orders placed on&nbsp;our&nbsp;websites may be delivered by one of several different carriers and shipping methods, therefore, tracking availability may vary depending on:</strong></p> <ul> <li><strong>The type of product you purchased</strong></li> <li><strong>The ‘How to get it’ method you selected during checkout</strong></li> <li><strong>The carrier that is delivering your product(s).</strong></li> </ul> <p>Occasionally, orders are delivered via a carrier that does not offer the ability to track a package. In these rare instances, “Order Status / Tracking” on the website will not offer tracking information, but will still offer order status and other details.</p> <p>Store Pickup orders will not be assigned tracking numbers. Order status for Store Pickup orders will be available within 15 minutes in the “Order Status/Tracking” area of our website. Order status will also be communicated via the order emails.<br><br></p> &nbsp; <strong>How is order status different from tracking information?</strong> <hr class="hd_rule2"> <p>Your <strong>Order Status</strong> is supplied by&nbsp;us, and represents what is happening with your order between the time you place it and the time it ships from our warehouse. Once your order leaves our warehouse, it is handled by a carrier (such as FedEx, USPS or UPS) that may provide <strong>Tracking Information</strong> which will allow you to keep track of your order from the time it leaves our warehouse to the time it reaches its destination*. The tracking information is accessible from “My Accout / Tracking” on our website when it becomes available.</p> <i>*Carrier-provided tracking information may not be available for up to 48 hours after a product is shipped from our warehouse.</i> &nbsp;<br><br> <strong>What if the estimated delivery date has passed and I still don’t have my order?</strong> <hr class="hd_rule2"> <p>Please note that Estimated Delivery Dates are estimates only, and are not guaranteed. Due to many factors, Estimated Delivery Dates can also change between the time you place the order and receive an order confirmation. We do our best to provide accurate estimates and provide you with several other resources for tracking your order, such as order detail and tracking links. It’s also important to note that if you selected our Pay in Store payment option, your order will not ship until payment is received in full.</p> <p>Orders that are shipped via a trackable method (such as UPS) will have tracking information available in Your Account. <br><br>Please check this information if available and read through the following options:</p> <ul> <li>If the tracking information indicates the package has been delivered, please check with your neighbors or family members. Packages are occasionally left with neighbors, a building manager, or are placed somewhere relatively safe such as your porch, garage, or even behind bushes.</li> <li>If the tracking information indicates the package is being returned to us, or if the address is incorrect, it may have been undeliverable.</li> </ul> <p>If there is no tracking information, or you cannot locate the package and it is not being returned as undeliverable, please feel free to contact an online customer service specialist for assistance at <span style="color: #3366ff;">support@graceframe.com</span></p>',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'Shipping Policy',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => 'Shipping Policy',
        'gp_title' => 'Shipping Policy',
        'tw_title' => 'Shipping Policy',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'
        ],
        [
        'title' => 'Terms of Service',
        'slug' => Str::slug('tos'),
        'content' => '<h2> Web Site Terms and Conditions of Use </h2> <h3> 1. Terms </h3> <p> By accessing this web site, you are agreeing to be bound by these web site Terms and Conditions of Use, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this web site are protected by applicable copyright and trade mark law. </p> <h3> 2. Use License </h3> <ol type="a"> <li>Permission is granted to temporarily download one copy of the materials (information or software) on GraceWood LLC&#39;s web site for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not: <ol type="i"> <li>modify or copy the materials; </li> <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial); </li> <li>attempt to decompile or reverse engineer any software contained on GraceWood LLC web site; </li> <li>remove any copyright or other proprietary notations from the materials; or </li> <li>transfer the materials to another person or "mirror" the materials on any other server. </li> </ol> </li> <li>This license shall automatically terminate if you violate any of these restrictions and may be terminated by GraceWood LLC at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format. </li> </ol> <h3> 3. Disclaimer </h3> <ol type="a"> <li>The materials on GraceWood web site are provided "as is". GraceWood LLC makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, GraceWood LLC does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site. </li> </ol> <h3> 4. Limitations </h3> <p> In no event shall GraceWood LLC or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on GraceWood Internet site, even if GraceWood LLC or a GraceWood LLC authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you. </p> <h3> 5. Revisions and Errata </h3> <p> The materials appearing on GraceWood web site could include technical, typographical, or photographic errors. GraceWood LLC does not warrant that any of the materials on its web site are accurate, complete, or current. GraceWood LLC may make changes to the materials contained on its web site at any time without notice. GraceWood LLC does not, however, make any commitment to update the materials. </p> <h3> 6. Links </h3> <p> GraceWood LLC has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by GraceWood LLC of the site. Use of any such linked web site is at the user own risk. </p> <h3> 7. Site Terms of Use Modifications </h3> <p> GraceWood LLC may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use. </p> <h3> 8. Governing Law </h3> <p> Any claim relating to GraceWood web site shall be governed by the laws of the State of Utah without regard to its conflict of law provisions. </p> <p> General Terms and Conditions applicable to Use of a Web Site. </p>',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'About Us',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => '',
        'gp_title' => '',
        'tw_title' => '',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'
        ],
        [
        'title' => 'Privacy Policy',
        'slug' => Str::slug('pp'),
        'content' => '<h2>Privacy Policy</h2> <p>    Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.</p> <ul> <li> Before or at the time of collecting personal information, we will identify the purposes for which information is being collected. </li> <li> We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law. </li> <li> We will only retain personal information as long as necessary for the fulfillment of those purposes. </li> <li> We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. </li> <li> Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. </li> <li> We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification. </li> <li> We will make readily available to customers information about our policies and practices relating to the management of personal information. </li> </ul> <p>We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.</p>',
        'has_product_link' => false,
        'product_link_nofollow' => false,
        'section_id' => null,
        'is_draft' => false,
        'excerpt' => null,
        'author_id' => 1,
        'meta_title' => 'Privacy Policy',
        'meta_description' => null,
        'meta_keywords' => null,
        'fb_title' => 'Privacy Policy',
        'gp_title' => 'Privacy Policy',
        'tw_title' => 'Privacy Policy',
        'link_to_product_title' => null,
        'link_to_product' => null,
        'created_at' => new DateTime,
        'published_at' => new DateTime,
        'updated_at' => new DateTime,
        'added_on' => new DateTime,
        'is_published' => true,
        'lang' => 'en'
        ]];
        DB::table('pages')->insert($article);
    }

}
